services:
  db:
    image: postgres:15-alpine
    container_name: mvp_taskclean_db_container
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mvp_taskclean_backend_container
    # Comando para iniciar o Node.js em modo de inspeção (debug)
    command: sh -c "node --inspect=0.0.0.0:9229 server.js"
    ports:
      - "3001:3001"
      - "9229:9229" # Expõe a porta de depuração
    env_file:
      - ./.env     # Garante que as credenciais da AWS sejam carregadas
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  db_data: